export const videoCategories = [
    { id: 'cat-1', name: 'Sales Fundamentals', description: 'Core sales skills every BCH employee needs', sortOrder: 1 },
    { id: 'cat-2', name: 'Product Knowledge', description: 'Deep dives into our product catalogue', sortOrder: 2 },
    { id: 'cat-3', name: 'Objection Handling', description: 'How to handle common customer objections', sortOrder: 3 },
    { id: 'cat-4', name: 'Customer Psychology', description: 'Understanding what makes customers buy', sortOrder: 4 },
    { id: 'cat-5', name: 'Closing Techniques', description: 'Proven methods to close the sale', sortOrder: 5 },
  ];

export const videos = [
    { id: 'vid-01', title: 'How to Greet a Customer', description: 'First impressions matter — learn the 10-second greeting rule', youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', categoryId: 'cat-1', durationMinutes: 5, sortOrder: 1 },
    { id: 'vid-02', title: 'Asking the Right Questions', description: 'Open-ended questions that uncover customer needs', youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', categoryId: 'cat-1', durationMinutes: 7, sortOrder: 2 },
    { id: 'vid-03', title: 'Body Language in Sales', description: 'Non-verbal cues that build trust with customers', youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', categoryId: 'cat-1', durationMinutes: 6, sortOrder: 3 },
    { id: 'vid-04', title: 'Understanding Bike Types', description: 'MTB vs Hybrid vs Road vs City — know what to recommend', youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', categoryId: 'cat-2', durationMinutes: 10, sortOrder: 1 },
    { id: 'vid-05', title: 'Choosing the Right Size Bike', description: 'Size chart, test fit, and why it matters for safety', youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', categoryId: 'cat-2', durationMinutes: 8, sortOrder: 2 },
    { id: 'vid-06', title: 'Gears and Brakes Explained', description: 'How to explain gear systems and brake types to customers', youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', categoryId: 'cat-2', durationMinutes: 12, sortOrder: 3 },
    { id: 'vid-07', title: '"It\'s Too Expensive" — How to Respond', description: 'Reframe price as value, not cost', youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', categoryId: 'cat-3', durationMinutes: 6, sortOrder: 1 },
    { id: 'vid-08', title: '"I Found It Cheaper Online"', description: 'How to compete with online prices using after-sales value', youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', categoryId: 'cat-3', durationMinutes: 7, sortOrder: 2 },
    { id: 'vid-09', title: 'Why Customers Buy — Psychology Basics', description: 'Emotional vs rational buying and how to use both', youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', categoryId: 'cat-4', durationMinutes: 9, sortOrder: 1 },
    { id: 'vid-10', title: 'Festival Season Selling', description: 'How to maximize sales during Dasara, Diwali, and holidays', youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', categoryId: 'cat-4', durationMinutes: 8, sortOrder: 2 },
    { id: 'vid-11', title: 'Closing the Sale', description: 'Proven closing techniques that feel natural, not pushy', youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', categoryId: 'cat-5', durationMinutes: 10, sortOrder: 1 },
    { id: 'vid-12', title: 'Getting the Follow-Up Right', description: 'WhatsApp follow-up templates and timing', youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', categoryId: 'cat-5', durationMinutes: 6, sortOrder: 2 },
  ];

export const achievements = [
    { id: 'ach-1', name: 'First Steps', description: 'Complete your first quiz', icon: 'star', criteriaType: 'quizzes_passed', criteriaValue: 1, xpReward: 50 },
    { id: 'ach-2', name: 'Quiz Master', description: 'Pass 10 quizzes', icon: 'trophy', criteriaType: 'quizzes_passed', criteriaValue: 10, xpReward: 200 },
    { id: 'ach-3', name: 'Role Player', description: 'Complete 5 AI practice sessions', icon: 'theater', criteriaType: 'roleplay_count', criteriaValue: 5, xpReward: 150 },
    { id: 'ach-4', name: 'Streak Starter', description: 'Maintain a 3-day streak', icon: 'flame', criteriaType: 'streak_days', criteriaValue: 3, xpReward: 100 },
    { id: 'ach-5', name: 'On Fire', description: 'Maintain a 7-day streak', icon: 'fire', criteriaType: 'streak_days', criteriaValue: 7, xpReward: 250 },
    { id: 'ach-6', name: 'Unstoppable', description: 'Maintain a 30-day streak', icon: 'rocket', criteriaType: 'streak_days', criteriaValue: 30, xpReward: 500 },
    { id: 'ach-7', name: 'Video Learner', description: 'Watch 10 training videos', icon: 'play', criteriaType: 'videos_watched', criteriaValue: 10, xpReward: 150 },
    { id: 'ach-8', name: 'Rising Star', description: 'Earn 500 XP', icon: 'trending-up', criteriaType: 'xp_total', criteriaValue: 500, xpReward: 100 },
    { id: 'ach-9', name: 'Sales Pro', description: 'Earn 2000 XP', icon: 'award', criteriaType: 'xp_total', criteriaValue: 2000, xpReward: 300 },
    { id: 'ach-10', name: 'BCH Champion', description: 'Earn 5000 XP', icon: 'crown', criteriaType: 'xp_total', criteriaValue: 5000, xpReward: 500 },
  ];

export const scenarios = [
    {
      id: 'sc-walk-in',
      title: 'Walk-in Customer',
      type: 'walk-in',
      description: 'A customer walks into the showroom browsing bikes. Convert them into a buyer.',
      checklist: [
        { step: 'Greet within 10 seconds with a warm smile', done: false },
        { step: 'Ask open-ended question: What brings you in today?', done: false },
        { step: 'Identify their need: commute, fitness, child, or hobby', done: false },
        { step: 'Show maximum 3 relevant models (not more)', done: false },
        { step: 'Highlight USPs specific to their need', done: false },
        { step: 'Let them touch/sit on the bike', done: false },
        { step: 'Handle price objection with value framing', done: false },
        { step: 'Offer test ride if possible', done: false },
        { step: 'Close with urgency: stock/offer/season', done: false },
        { step: 'If not buying today, get their phone number', done: false },
      ],
      tips: ['Never follow the customer around — give space but stay available', 'Mirror their energy level', 'Always know today\'s offers before floor duty'],
      difficulty: 'beginner',
      sortOrder: 1,
    },
    {
      id: 'sc-phone',
      title: 'Phone Enquiry',
      type: 'phone',
      description: 'A potential customer calls asking about a specific bike or price. Convert the call into a showroom visit.',
      checklist: [
        { step: 'Answer within 3 rings, state your name and BCH', done: false },
        { step: 'Listen fully — do not interrupt their question', done: false },
        { step: 'Ask: Which bike are you looking at? / What is it for?', done: false },
        { step: 'Give price range, not exact price (create reason to visit)', done: false },
        { step: 'Mention current offer or exclusive in-store deal', done: false },
        { step: 'Invite them to visit: We have it ready for a test ride', done: false },
        { step: 'Get their name and WhatsApp number', done: false },
        { step: 'Send follow-up message within 5 minutes', done: false },
      ],
      tips: ['Smile while talking — it changes your voice tone', 'Never say NO directly, always redirect', 'If you don\'t know the answer, say: Let me check and call you back in 5 minutes'],
      difficulty: 'beginner',
      sortOrder: 2,
    },
    {
      id: 'sc-repeat',
      title: 'Repeat Customer / Service Visit',
      type: 'repeat',
      description: 'An existing customer visits for service. Upsell accessories or a new bike for a family member.',
      checklist: [
        { step: 'Greet by name if you recognize them', done: false },
        { step: 'Ask about their current bike experience', done: false },
        { step: 'Suggest relevant accessories (lock, helmet, light)', done: false },
        { step: 'Mention new arrivals in their preferred category', done: false },
        { step: 'Ask: Anyone else in the family looking for a bike?', done: false },
        { step: 'Offer loyalty discount or referral benefit', done: false },
        { step: 'Thank them for choosing BCH', done: false },
      ],
      tips: ['Repeat customers are 5x easier to sell to than new ones', 'Remember details from last visit if possible', 'A small gesture (free air fill, chain oil) goes a long way'],
      difficulty: 'intermediate',
      sortOrder: 3,
    },
    {
      id: 'sc-festival',
      title: 'Festival / Seasonal Buyer',
      type: 'festival',
      description: 'Customer shopping during a festival season (Dasara, Diwali, New Year). They expect deals.',
      checklist: [
        { step: 'Acknowledge the festival: Happy Dasara! Great time to buy', done: false },
        { step: 'Show the festival special offers prominently', done: false },
        { step: 'Create urgency: Offer valid only till [date]', done: false },
        { step: 'Bundle deals: Bike + helmet + lock at special price', done: false },
        { step: 'Highlight gifting angle: Perfect gift for your child', done: false },
        { step: 'Offer EMI options if price is a concern', done: false },
        { step: 'Close confidently: Shall I bill this for you?', done: false },
      ],
      tips: ['Festival buyers are emotionally motivated — tap into that', 'Always know the exact offer details and end dates', 'Gift wrapping or a small freebie seals the deal'],
      difficulty: 'beginner',
      sortOrder: 4,
    },
    {
      id: 'sc-parent',
      title: 'Parent Buying for Child',
      type: 'parent',
      description: 'A parent comes in to buy a bike for their child. They care about safety and value.',
      checklist: [
        { step: 'Ask the child\'s age and height', done: false },
        { step: 'Recommend the right size (never upsell wrong size)', done: false },
        { step: 'Show safety features: training wheels, chain guard, brakes', done: false },
        { step: 'Let the child sit on the bike and react', done: false },
        { step: 'Talk to the parent about durability and warranty', done: false },
        { step: 'Suggest helmet and safety gear as add-on', done: false },
        { step: 'If child is excited, use that energy to close', done: false },
        { step: 'Mention exchange policy as they grow', done: false },
      ],
      tips: ['The child\'s excitement is your best sales tool', 'Never recommend a bigger size to grow into — it\'s dangerous and parents know', 'Parents trust you more when you prioritize safety over price'],
      difficulty: 'beginner',
      sortOrder: 5,
    },
    {
      id: 'sc-comparison',
      title: 'Price Comparison Shopper',
      type: 'comparison',
      description: 'Customer has checked prices online or at competitors. They want the best deal.',
      checklist: [
        { step: 'Acknowledge: Great that you\'re doing your research', done: false },
        { step: 'Ask what other options they are considering', done: false },
        { step: 'Never badmouth competitors', done: false },
        { step: 'Highlight BCH advantages: service, warranty, local support', done: false },
        { step: 'Show total cost of ownership, not just sticker price', done: false },
        { step: 'Mention free services included (assembly, first service, air)', done: false },
        { step: 'If they mention online price, explain after-sales difference', done: false },
        { step: 'Offer price match if within policy', done: false },
        { step: 'Close with trust: We are here for you after the sale too', done: false },
      ],
      tips: ['Online prices don\'t include assembly, warranty claims hassle, or local support', 'Be confident — never act desperate about pricing', 'The customer chose to come to a physical store for a reason — find out why'],
      difficulty: 'advanced',
      sortOrder: 6,
    },
  ];

export const quizzes = [
    {
      id: 'quiz-sales-101',
      title: 'Sales Fundamentals',
      description: 'Core selling skills every BCH employee must know',
      type: 'general',
      difficulty: 'beginner',
      passingScore: 70,
      xpReward: 75,
      questions: [
        { question: 'A customer walks in and is browsing bikes. What should you do first?', options: ['Tell them the prices immediately', 'Greet them warmly within 10 seconds', 'Wait for them to ask you something', 'Start showing the most expensive bike'], correctIndex: 1, explanation: 'Always greet within 10 seconds. A warm greeting builds rapport and shows you care.' },
        { question: 'How many bike options should you show a walk-in customer?', options: ['1 — the best one', '2 to 3 relevant options', '5 or more so they have lots of choice', 'All bikes in their budget range'], correctIndex: 1, explanation: 'Too many choices cause confusion. Show 2-3 relevant options based on their need.' },
        { question: 'A customer says "I\'m just looking." What\'s the best response?', options: ['"OK let me know if you need anything" and walk away', '"No problem! Are you looking for yourself or someone else?"', '"We have a sale going on, let me show you"', 'Follow them around the store silently'], correctIndex: 1, explanation: 'An open-ended question keeps the conversation going without being pushy.' },
        { question: 'What is the most important thing to identify about a walk-in customer?', options: ['Their budget', 'Their need — commute, fitness, child, or hobby', 'Whether they will buy today', 'Which brand they prefer'], correctIndex: 1, explanation: 'Understanding the NEED lets you recommend the right bike. Budget comes second.' },
        { question: 'When should you discuss price?', options: ['As soon as possible', 'Only after understanding their need and showing value', 'Only if they ask', 'Never — let them see the price tag'], correctIndex: 1, explanation: 'Build value first. Once they see how the bike solves their need, price becomes secondary.' },
        { question: 'A customer is about to leave without buying. What should you do?', options: ['Let them go — don\'t be pushy', 'Ask for their phone number for follow-up', 'Offer a bigger discount', 'Block the exit and convince them'], correctIndex: 1, explanation: 'Getting their contact info lets you follow up. 80% of sales happen in follow-up, not the first visit.' },
        { question: 'What creates urgency in a sale?', options: ['Saying "buy now or never"', 'Mentioning limited stock, current offers, or seasonal timing', 'Lying about price increases', 'Refusing to let them think about it'], correctIndex: 1, explanation: 'Real urgency — limited stock, expiring offers — is honest and effective.' },
        { question: 'How should you handle a customer who wants to "think about it"?', options: ['"Sure, take your time" and forget about them', 'Agree, get their number, and follow up in 2 days', 'Pressure them to decide now', 'Offer a huge discount immediately'], correctIndex: 1, explanation: 'Respect their process but stay in touch. A polite follow-up often closes the sale.' },
      ],
    },
    {
      id: 'quiz-objections',
      title: 'Handling Objections',
      description: 'Turn customer concerns into opportunities',
      type: 'general',
      difficulty: 'intermediate',
      passingScore: 70,
      xpReward: 100,
      questions: [
        { question: 'Customer: "This bike is too expensive." Best response?', options: ['"It\'s actually quite cheap for the quality"', '"I understand. Let me show you what makes this worth every rupee — the features, warranty, and after-sales support"', '"Let me check if I can give you a discount"', '"You get what you pay for"'], correctIndex: 1, explanation: 'Acknowledge the concern, then reframe with value. Never dismiss their feeling.' },
        { question: 'Customer: "I found it cheaper online." What do you say?', options: ['"Online shops are unreliable"', '"We can\'t match online prices"', '"Great research! With us you get free assembly, warranty service at your doorstep, and we\'re here if anything goes wrong"', '"That\'s a fake listing"'], correctIndex: 2, explanation: 'Highlight BCH advantages — assembly, local service, warranty — without badmouthing competitors.' },
        { question: 'Customer: "I need to ask my spouse first." What\'s the right approach?', options: ['"Bring them in! I\'d love to show them too. What time works?"', '"It\'s just a bike, you don\'t need permission"', '"The offer ends today"', '"OK, bye"'], correctIndex: 0, explanation: 'Invite the spouse in. Make it easy for them to return together.' },
        { question: 'What should you NEVER do when a customer raises an objection?', options: ['Listen carefully', 'Acknowledge their concern', 'Argue or get defensive', 'Ask a follow-up question'], correctIndex: 2, explanation: 'Arguing kills the sale. Listen, acknowledge, then respond with value.' },
        { question: 'Customer: "The bike next door is the same but cheaper." Best approach?', options: ['Match their price immediately', 'Ask what is included — often the "cheaper" option lacks service, warranty, or accessories', 'Say the other shop sells duplicates', 'Give up on the sale'], correctIndex: 1, explanation: 'Compare total value, not just sticker price. BCH includes assembly, service, and support.' },
        { question: 'Customer: "I don\'t think my child needs such an expensive bike." What do you say?', options: ['"You\'re right, let me show you a cheaper one"', '"A quality bike is safer — better brakes, stronger frame, and it lasts through growth spurts so you save long-term"', '"This is our cheapest kids bike"', '"Expensive means better"'], correctIndex: 1, explanation: 'For parents, connect price to SAFETY and long-term value. They will spend more for their child\'s safety.' },
      ],
    },
    {
      id: 'quiz-product',
      title: 'Product Knowledge',
      description: 'Know your bikes and parts inside out',
      type: 'product',
      difficulty: 'beginner',
      passingScore: 70,
      xpReward: 75,
      questions: [
        { question: 'A customer wants a bike for daily office commute (5 km). What type do you recommend?', options: ['Mountain bike with full suspension', 'Single-speed city bike or hybrid', 'BMX bike', 'Road racing bike'], correctIndex: 1, explanation: 'For short commutes, a city or hybrid bike is practical, comfortable, and low maintenance.' },
        { question: 'What size bike is right for a 10-year-old child (around 4\'5")?', options: ['20 inch', '24 inch', '26 inch', '16 inch'], correctIndex: 0, explanation: '20-inch wheels are ideal for ages 8-11 and heights around 4\'2" to 4\'9".' },
        { question: 'What does "single speed" (SS) mean?', options: ['The bike has only one gear — no gear shifting', 'The bike can only go one speed', 'The bike has a single brake', 'The bike has one wheel'], correctIndex: 0, explanation: 'Single speed = one gear ratio. Simple, low maintenance, great for flat terrain commuting.' },
        { question: 'How often should a daily rider get a General Service?', options: ['Once a year', 'Every 2-3 months', 'Only when something breaks', 'Every week'], correctIndex: 1, explanation: 'Every 2-3 months keeps the bike safe and prevents expensive breakdowns.' },
        { question: 'Customer asks: "What\'s the difference between disc brakes and V-brakes?"', options: ['No difference', 'Disc brakes work better in rain and last longer; V-brakes are simpler and cheaper', 'V-brakes are always better', 'Disc brakes are only for motorcycles'], correctIndex: 1, explanation: 'Disc brakes offer superior stopping in all conditions. V-brakes are budget-friendly and easy to maintain.' },
        { question: 'A customer\'s chain is skipping. What parts likely need replacing?', options: ['Only the chain', 'Chain and freewheel/cassette together', 'The entire drivetrain', 'Nothing — just needs oil'], correctIndex: 1, explanation: 'A worn chain wears the freewheel teeth. Replace both together for reliable shifting.' },
        { question: 'What is a Tyre Liner used for?', options: ['Making tyres look shiny', 'Preventing punctures by sitting between tyre and tube', 'Increasing tyre grip', 'Reducing tyre weight'], correctIndex: 1, explanation: 'Tyre liners block thorns and glass from reaching the tube — prevents 90% of flats.' },
        { question: 'Which accessory should you recommend with EVERY new bike sale?', options: ['Water bottle', 'Helmet and lock', 'GPS tracker', 'Racing gloves'], correctIndex: 1, explanation: 'Helmet (safety) and lock (theft protection) are the two must-have accessories for every cyclist.' },
      ],
    },
    {
      id: 'quiz-customer',
      title: 'Customer Scenarios',
      description: 'Handle real-world situations at BCH',
      type: 'scenario',
      difficulty: 'advanced',
      passingScore: 70,
      xpReward: 125,
      questions: [
        { question: 'A parent wants to buy a 26" bike for their 8-year-old "so they can grow into it." What do you do?', options: ['Agree and sell the bigger bike', 'Politely explain that an oversized bike is unsafe — wrong size means they can\'t reach brakes or ground properly', 'Say nothing and let them decide', 'Upsell to an even bigger bike'], correctIndex: 1, explanation: 'NEVER sell the wrong size for a child. Safety over sale. This builds trust — they\'ll come back.' },
        { question: 'It\'s Dasara season. A customer walks in with family. How do you approach them?', options: ['Focus only on the person who looks like the buyer', '"Happy Dasara! Looking for a festival gift? We have special offers running this week"', '"What\'s your budget?"', 'Wait for them to approach you'], correctIndex: 1, explanation: 'Acknowledge the festival, engage the whole family, and mention offers. Festival buyers are emotionally ready to buy.' },
        { question: 'A customer is angry because their recent purchase has a flat tyre. What do you do?', options: ['"Punctures aren\'t covered under warranty"', '"Sorry to hear that! Let me fix it right away for free. Flats happen but we\'ve got you covered"', '"You must have ridden over a nail"', 'Ask them to come back tomorrow'], correctIndex: 1, explanation: 'Fix it immediately with empathy. A free repair costs you ₹50 but earns a customer for life.' },
        { question: 'A customer bought a bike last month and now wants to return it. Store policy is no returns. What do you do?', options: ['Strictly refuse and point to the receipt', 'Listen to their reason, offer exchange or store credit, and escalate to the owner if needed', 'Accept the return no questions asked', 'Argue with them'], correctIndex: 1, explanation: 'Listen first. Often the issue can be resolved with an exchange, adjustment, or store credit. Escalate major cases.' },
        { question: 'You notice a customer looking at bikes for 15+ minutes but hasn\'t asked for help. What do you do?', options: ['Leave them alone — they\'ll ask if they need help', 'Walk over and casually say "Found anything you like? I can help you compare"', 'Start a sales pitch immediately', 'Stare at them from the counter'], correctIndex: 1, explanation: 'A gentle check-in after 10-15 minutes shows you care. Many customers want help but are too shy to ask.' },
        { question: 'A competitor\'s customer comes in for service on their bike (not bought from BCH). Do you service it?', options: ['No — we only service bikes bought from us', 'Yes — service it well. They\'ll remember BCH when buying their next bike', 'Yes, but charge extra', 'Tell them to go back where they bought it'], correctIndex: 1, explanation: 'Servicing any bike builds goodwill. Many customers switch to BCH after experiencing our service quality.' },
      ],
    },
  ];

export const ecycles = [
    {
      id: 'prod-doodle',
      name: 'EMotorad Doodle',
      brand: 'EMotorad',
      category: 'E-Cycles',
      price: 56000,
      imageUrl: 'https://cdn.bikedekho.com/processedimages/emotorad/doodle/source/doodle695f481ab1d07.jpg',
      usps: [
        'BCH #1 seller — 115+ units sold',
        'The "cool kid" cycle — design IS the identity',
        'Fat tyres for Bangalore roads',
        '25 kmph speed lock (parent-safe)',
        'Rs. 7 per 100 km running cost',
        'Folds for easy storage',
      ],
      features: ['Fat tyre design', 'Throttle + pedal assist', 'LED display', 'Foldable frame', 'Removable battery', 'Front suspension', 'Disc brakes front & rear'],
      talkingPoints: [
        'This is not just a cycle — it is a STATUS SYMBOL for kids. 52% buy it because their friends will see it.',
        'Parents: Your kid hasn\'t touched his phone in 14 days after getting this.',
        'Charges overnight like a phone, lasts all weekend.',
        'Running cost: Rs. 7 for 100 km. Compare that to your auto-rickshaw fare.',
        'Speed locked at 25 kmph — your child cannot go dangerously fast.',
        'EMI available: Rs. 1,999/month — less than your monthly Swiggy bill.',
        'BCH provides 2-year free service with The Winner Package.',
      ],
      targetCustomer: 'Kids 14-17 (status-driven, want to be the coolest in friend group) + Parents (want kid off screens)',
      commonObjections: [
        { objection: 'Rs. 56,000 is too much for a cycle', response: 'Think of it as Rs. 1,999/month EMI — less than Netflix + Swiggy combined. Plus, it replaces auto fare, improves health, and gets your kid OFF the phone. That\'s a Rs. 2.2 lakh value.' },
        { objection: 'He won\'t use it after 3 months', response: 'E-cycles retain interest 300% longer than normal cycles because of the throttle and speed. Plus, with BCH Riders Club, your kid joins group rides every weekend — it stays fun.' },
        { objection: 'Is it safe for my kid?', response: 'Speed is locked at 25 kmph. It has disc brakes on both wheels. The fat tyres grip better than any regular cycle. We check 23 safety points before delivery.' },
        { objection: 'I found it cheaper online', response: 'Online price doesn\'t include assembly, warranty service, or someone to call when something goes wrong. With BCH, you get 2-year free service, same-day repairs, and an 8-mechanic team 10 minutes away.' },
        { objection: 'Roads are not safe', response: 'This is actually the EASIEST objection to handle. Acknowledge the fear, show the speed lock at 25 kmph, disc brakes, and fat tyre grip. Roads aren\'t safe for any vehicle — but this is the safest option at this speed.' },
      ],
    },
    {
      id: 'prod-trex',
      name: 'EMotorad T-Rex V3',
      brand: 'EMotorad',
      category: 'E-Cycles',
      price: 57999,
      imageUrl: 'https://cdn.bikedekho.com/processedimages/emotorad/t-rex-plus-v3/source/t-rex-plus-v3695f4ce382baa.jpg',
      usps: [
        'Full-size fat tyre MTB — feels like a REAL bike',
        'Longest range in lineup: 50-65 km per charge',
        'Larger 10.4Ah battery — weekend rides without worry',
        'Front suspension for rough Bangalore roads',
        '26" fat tyres eat potholes for breakfast',
        'Integrated rear rack — practical and tough',
      ],
      features: ['26" x 4.0" fat tyres', '250W rear hub motor', '36V 10.4Ah removable battery', 'Front suspension fork', 'Shimano 7-speed', 'Mechanical disc brakes', 'LCD display', 'Pedal assist + throttle', 'Rear rack', 'EMotorad app connectivity'],
      talkingPoints: [
        'This is for the rider who wants a FULL-SIZE mountain bike feel, not a foldable.',
        'The T-Rex has the biggest battery in the mid-range — 10.4Ah means 50-65 km range.',
        'Perfect for longer commutes or weekend trail rides with friends.',
        'Fat tyres + suspension = Bangalore roads feel smooth.',
        'Running cost same as Doodle: Rs. 7 for 100 km.',
        'Rear rack built in — carry bags, delivery, or a friend\'s backpack.',
      ],
      targetCustomer: 'Adults and older teens who want a serious MTB, adventure riders, longer commuters (8-15 km)',
      commonObjections: [
        { objection: 'It is heavier than the Doodle', response: 'Yes, it is a full-size 26" MTB — that weight gives you stability. The motor does the heavy lifting, so you won\'t feel the extra 3 kg while riding.' },
        { objection: 'Why not just buy a regular MTB?', response: 'A regular MTB costs Rs. 15-25K but you arrive sweaty. The T-Rex lets you arrive fresh — use throttle in traffic, pedal for exercise. Best of both worlds.' },
        { objection: 'It does not fold', response: 'Correct — and that is the point. Full-size frame = better stability, better comfort on long rides. If storage is tight, the Doodle folds. If riding experience is priority, the T-Rex wins.' },
      ],
    },
    {
      id: 'prod-x1',
      name: 'EMotorad X1',
      brand: 'EMotorad',
      category: 'E-Cycles',
      price: 32999,
      imageUrl: 'https://cdn.bikedekho.com/processedimages/emotorad/emotorad-x1/source/emotorad-x1695f4dbbba3eb.jpg',
      usps: [
        'Most affordable EMotorad e-cycle — gateway to electric',
        'Lightweight at ~19 kg — easy to handle',
        'Clean urban design — looks like a regular bike',
        'Perfect for short commutes (5-10 km)',
        'Quick 3-4 hour charge time',
      ],
      features: ['26" standard tyres', '250W rear hub motor', '36V 5.8Ah battery', 'Mechanical disc brakes', 'LED display', 'Pedal assist + throttle', 'Steel/Hi-tensile frame'],
      talkingPoints: [
        'Entry-level e-cycle — perfect for someone trying electric for the first time.',
        'At Rs. 33K, this is the most affordable way to go electric.',
        'Lightweight and simple — no complicated gears to confuse new riders.',
        'Range is 30-35 km — more than enough for daily school or office commute.',
        'Charges in just 3-4 hours — plug in when you get home, ready by evening.',
      ],
      targetCustomer: 'First-time e-cycle buyers, students, budget-conscious commuters, short-distance riders',
      commonObjections: [
        { objection: 'Range is less than Doodle', response: 'For a daily 5-10 km commute, 30 km range means you charge every 3 days, not daily. It is more than enough for most riders.' },
        { objection: 'It is steel frame, not aluminium', response: 'Steel is actually more durable and absorbs road vibrations better. At this price point, you get a tougher frame that lasts.' },
      ],
    },
    {
      id: 'prod-x2',
      name: 'EMotorad X2',
      brand: 'EMotorad',
      category: 'E-Cycles',
      price: 41999,
      imageUrl: 'https://cdn.bikedekho.com/processedimages/emotorad/x2/source/x2695f4e43b3b0d.jpg',
      usps: [
        'Sweet spot of price and performance',
        'Aluminium frame — lighter and corrosion-resistant',
        '27.5" wheels for faster rolling',
        'Removable battery — charge indoors',
        'Front suspension for city comfort',
      ],
      features: ['27.5" standard tyres', '250W rear hub motor', '36V 7.65Ah removable battery', 'Aluminium alloy frame', 'Front suspension', 'Shimano 7-speed', 'Mechanical disc brakes', 'LCD display', 'Pedal assist + throttle', 'EMotorad app'],
      talkingPoints: [
        'The X2 is the "Goldilocks" e-cycle — not too basic, not too expensive.',
        'Aluminium frame means lighter rides and no rust — important in Bangalore weather.',
        '27.5" wheels roll faster than 26" — covers more distance per pedal stroke.',
        'Removable battery means you can take the battery to your flat for charging — no need to bring the bike inside.',
        '7-speed Shimano gears for hills and flat roads.',
      ],
      targetCustomer: 'Mid-budget commuters, riders upgrading from regular cycles, daily 8-12 km commuters',
      commonObjections: [
        { objection: 'Why not spend a bit more for the Doodle?', response: 'The X2 is better for pure commuting — 27.5" wheels are faster on roads. The Doodle is about style and fat tyres. Depends on what you want — speed or style.' },
        { objection: 'No fat tyres?', response: 'Standard tyres are actually better for road commuting — less rolling resistance, faster, and lighter. Fat tyres are for style and off-road.' },
      ],
    },
    {
      id: 'prod-x3',
      name: 'EMotorad X3',
      brand: 'EMotorad',
      category: 'E-Cycles',
      price: 52999,
      imageUrl: 'https://cdn.bikedekho.com/processedimages/emotorad/x3/source/x3695f4f6ff37b5.jpg',
      usps: [
        'Premium commuter — largest battery in X-series',
        '10.4Ah battery for 50-60 km range',
        'Premium aluminium 6061 frame',
        'Best for daily commuters who need max range',
        'Integrated lights for safety',
      ],
      features: ['27.5" tyres', '250W rear hub motor', '36V 10.4Ah removable battery', 'Aluminium 6061 frame', 'Front suspension', 'Shimano 7-speed', 'Mechanical disc brakes', 'LCD display', 'Pedal assist + throttle', 'Integrated front/rear lights', 'EMotorad app'],
      talkingPoints: [
        'The X3 has the biggest battery in the commuter range — 10.4Ah means 50-60 km range.',
        'Charge on Sunday night, ride all week for short commutes.',
        'Integrated lights mean no extra accessories needed — ride safely day and night.',
        'Premium 6061 aluminium is the same alloy used in aircraft — strong and light.',
        'If you commute 15+ km daily, the X3 pays for itself vs petrol in 12-14 months.',
      ],
      targetCustomer: 'Long-distance commuters (15+ km daily), riders who want max range, premium buyers who don\'t want fat tyres',
      commonObjections: [
        { objection: 'Almost same price as Doodle — why not Doodle?', response: 'The X3 has 35% more range (60 km vs 45 km). If you commute long distance, that extra range is critical. The Doodle trades range for style and foldability.' },
      ],
    },
    {
      id: 'prod-desire',
      name: 'EMotorad Desire',
      brand: 'EMotorad',
      category: 'E-Cycles',
      price: 42999,
      imageUrl: 'https://cdn.bikedekho.com/processedimages/emotorad/dope/source/dope6924372432777.jpg',
      usps: [
        'Step-through frame — easy to mount/dismount',
        'Designed for women and senior citizens',
        'Saree-friendly and kurta-friendly design',
        'Comfortable upright riding position',
        'Rear rack + front basket option',
      ],
      features: ['26" standard tyres', '250W rear hub motor', '36V 7.65Ah removable battery', 'Aluminium alloy step-through frame', 'Shimano 7-speed', 'Mechanical disc brakes', 'LCD display', 'Pedal assist + throttle', 'Rear rack', 'EMotorad app'],
      talkingPoints: [
        'The ONLY e-cycle in the range designed specifically for easy mounting — step-through frame.',
        'Perfect for mothers, grandparents, or anyone who finds swinging a leg over difficult.',
        'Saree-friendly, kurta-friendly — no fabric catching on the top tube.',
        'Same motor and battery as X2, but more comfortable riding position.',
        'Rear rack built in — carry grocery bags, tiffin, or a small child seat.',
      ],
      targetCustomer: 'Women riders, senior citizens, casual commuters who want comfort, families needing a second e-cycle',
      commonObjections: [
        { objection: 'E-cycles are too fast for women', response: 'Speed is locked at 25 kmph for ALL e-cycles. The Desire has the same safety features as every other model — disc brakes, speed lock. And the step-through frame is actually SAFER for mounting and dismounting.' },
        { objection: 'My mother/wife won\'t ride an e-cycle', response: 'Bring them for a test ride. The step-through frame and pedal assist make it effortless. 9 out of 10 women who test ride end up smiling — the assist makes riding feel like magic.' },
      ],
    },
    {
      id: 'prod-emx',
      name: 'EMotorad EMX',
      brand: 'EMotorad',
      category: 'E-Cycles',
      price: 42999,
      imageUrl: 'https://cdn.bikedekho.com/processedimages/emotorad/emx/source/emx695f48e73fcf8.jpg',
      usps: [
        'Foldable like Doodle but with STANDARD tyres — lighter!',
        'Best for apartment dwellers — folds into closet',
        'Lighter than Doodle (~20 kg vs ~23 kg)',
        'Smoother and faster on roads than fat tyres',
        'Same motor and battery as Doodle',
      ],
      features: ['20" standard tyres', '250W rear hub motor', '36V 7.65Ah removable battery', 'Aluminium alloy foldable frame', 'Shimano 7-speed', 'Mechanical disc brakes', 'LCD display', 'Pedal assist + throttle', 'EMotorad app'],
      talkingPoints: [
        'Think of the EMX as the Doodle\'s practical sibling — same foldable frame, lighter and faster.',
        'Standard 20" tyres roll smoother and faster on city roads compared to fat tyres.',
        'At ~20 kg, it is 3 kg lighter than the Doodle — easier to carry upstairs.',
        'Folds compact — fits in car boot, under office desk, or in apartment closet.',
        'Same Rs. 7 per 100 km running cost.',
      ],
      targetCustomer: 'Urban apartment dwellers, office commuters who store bike at desk, metro + last-mile riders, people who want foldable but not fat tyre',
      commonObjections: [
        { objection: 'Why not the Doodle? It looks cooler', response: 'If looks are priority, Doodle wins. But if you commute daily and carry it upstairs, the EMX is 3 kg lighter and rolls smoother. It depends on style vs practicality.' },
      ],
    },
    {
      id: 'prod-lile',
      name: 'EMotorad Lil E',
      brand: 'EMotorad',
      category: 'E-Cycles',
      price: 22999,
      imageUrl: 'https://cdn.bikedekho.com/processedimages/emotorad/neo/source/neo695f4a15a98bb.jpg',
      usps: [
        'Made for KIDS — speed-limited for safety',
        'Most affordable e-cycle in the lineup',
        'Lightweight at ~15 kg — kids can handle it',
        'Bright fun colors — kids love it',
        'Parents love the speed limiter',
      ],
      features: ['16" or 20" wheels', '150-250W rear hub motor (speed limited)', '24-36V removable battery', 'Speed limiter (15-20 kmph max)', 'V-brakes or mechanical disc brakes', 'Single speed', 'LED display', 'Pedal assist + throttle'],
      talkingPoints: [
        'The Lil E is the ONLY e-cycle designed specifically for kids under 12.',
        'Speed is capped at 15-20 kmph — significantly slower than the adult models at 25 kmph.',
        'At ~15 kg, kids can pick it up and maneuver it easily.',
        'Battery lasts 15-20 km — plenty for neighbourhood rides and park trips.',
        'This is the PERFECT gift for birthdays and festivals — parents love the safety, kids love the speed.',
        'At Rs. 23K, it is the most affordable way to get your kid started on electric.',
      ],
      targetCustomer: 'Kids aged 5-12, parents buying gifts, festival/birthday shoppers',
      commonObjections: [
        { objection: 'My kid will outgrow it', response: 'Kids outgrow regular cycles too. The Lil E gives them 2-3 years of riding. When they outgrow it, they upgrade to the Doodle — and we offer exchange value on the old one.' },
        { objection: 'Is 20 kmph safe for a kid?', response: '20 kmph is jogging speed — a fit adult runs faster than this. And it has brakes on both wheels. Much safer than a regular cycle going downhill with no speed limit.' },
        { objection: 'Too expensive for a kids cycle', response: 'A regular kids cycle is Rs. 8-15K and they ride it for a year before getting bored. The Lil E keeps them excited because of the motor — 300% longer engagement. Cost per month of use is actually lower.' },
      ],
    },
    {
      id: 'prod-basik',
      name: 'EMotorad Basik 1.0',
      brand: 'EMotorad',
      category: 'E-Cycles',
      price: 26999,
      imageUrl: 'https://cdn.bikedekho.com/processedimages/emotorad/ranger-e-cycle/source/ranger-e-cycle695f4ab9056cd.jpg',
      usps: [
        'Cheapest adult e-cycle from EMotorad',
        'Simple and reliable — no complicated features',
        'Quick 3-hour charge',
        'Perfect gateway to electric cycling',
      ],
      features: ['26" standard tyres', '250W rear hub motor', '36V 5.2Ah battery', 'Steel hi-tensile frame', 'V-brakes or mechanical disc', 'Single speed', 'Basic LED display', 'Pedal assist + throttle'],
      talkingPoints: [
        'At Rs. 27K, this is the most affordable way for an adult to go electric.',
        'Simple single-speed design — nothing to confuse or maintain.',
        'Charges in just 3 hours — fastest in the lineup.',
        '25-30 km range is perfect for daily 5-8 km commutes.',
        'If someone says "I want to TRY electric cycling but don\'t want to spend 50K" — this is the answer.',
      ],
      targetCustomer: 'First-time e-cycle buyers, students, delivery riders, extremely budget-conscious commuters',
      commonObjections: [
        { objection: 'Range is only 25-30 km', response: 'For a daily 5-8 km commute, you charge every 3-4 days. That is more than enough. And at Rs. 27K, you save Rs. 25-30K over the Doodle.' },
        { objection: 'Steel frame, not aluminium', response: 'Steel is tougher and cheaper to repair if damaged. For a daily workhorse bike, steel makes sense. Save the aluminium premium for when you upgrade.' },
      ],
    },
    {
      id: 'prod-hammerhead',
      name: 'EMotorad Hammerhead',
      brand: 'EMotorad',
      category: 'E-Cycles',
      price: 74999,
      imageUrl: 'https://cdn.bikedekho.com/processedimages/emotorad/viper/source/viper69e5d080c703d.jpg',
      usps: [
        'PREMIUM fat tyre MTB — top of the range',
        'HYDRAULIC disc brakes (only model with this)',
        'Biggest battery: 13Ah for 60-80 km range',
        'Suspension with lockout — trail or road',
        'Built for serious riders who want the BEST',
      ],
      features: ['26" x 4.0" fat tyres', '250-350W rear hub motor', '36V 13Ah removable battery', 'Aluminium 6061 frame', 'Hydraulic disc brakes', 'Front suspension with lockout', 'Shimano 7-speed', 'LCD display with full data', 'Pedal assist + throttle', 'Integrated lights', 'EMotorad app'],
      talkingPoints: [
        'The Hammerhead is the FLAGSHIP — if a customer says "give me the best," this is it.',
        'ONLY EMotorad model with hydraulic disc brakes — stopping power is on another level.',
        'Largest battery in the entire range: 13Ah = 60-80 km range. Weekend trip without charging.',
        'Suspension lockout means you lock it for smooth roads (efficiency) and unlock for trails (comfort).',
        'For the rich customer segment (37% of BCH clients) — don\'t talk price, talk quality.',
        'At Rs. 75K, this competes with entry-level motorcycles — but with zero fuel cost, zero insurance, zero license.',
      ],
      targetCustomer: 'Premium buyers (1L+ income), adventure enthusiasts, riders who want the absolute best, status-conscious adults',
      commonObjections: [
        { objection: 'Rs. 75K for a cycle?', response: 'Compare it to an entry-level motorcycle: Rs. 80K + Rs. 5K insurance + Rs. 4K/month petrol + license hassle. The Hammerhead costs Rs. 7 per 100 km, zero insurance, zero license. It SAVES you money.' },
        { objection: 'Too heavy at 29 kg', response: 'The motor makes weight irrelevant while riding. And the extra weight comes from the bigger battery (80 km range!) and hydraulic brakes. It is engineered heavy for a reason.' },
      ],
    },
  ];

export const bicycles = [
    // === RALEIGH MTB ===
    { id: 'bike-ral-terrain26', name: 'Raleigh Terrain 26', brand: 'Raleigh', category: 'MTB', price: 13000, usps: ['Heritage British brand (est. 1887)', 'Shimano 21-speed for all terrain', 'Front suspension for comfort'], features: ['Steel Hi-Ten frame', 'Shimano 21-speed (3x7)', 'V-brakes', '26" wheels', 'Front suspension hardtail'], talkingPoints: ['Raleigh is a 135+ year old brand — trust and durability built in.', 'Shimano 21-speed handles Bangalore hills easily.', 'Great entry MTB under Rs. 15K — better specs than Hero at this price.'], targetCustomer: 'Adults wanting a recreational MTB, first-time geared bike buyers', commonObjections: [{ objection: 'Never heard of Raleigh', response: 'Raleigh is one of the oldest cycle brands in the world — 1887! In India they are backed by TI Cycles, the largest manufacturer. Spare parts are easy to get.' }] },
    { id: 'bike-ral-terrain275', name: 'Raleigh Terrain 27.5', brand: 'Raleigh', category: 'MTB', price: 15500, usps: ['27.5" wheels — rolls better over obstacles', 'Shimano 21-speed', 'Front suspension'], features: ['Steel Hi-Ten frame', 'Shimano 21-speed', 'V-brakes', '27.5" wheels', 'Front suspension hardtail'], talkingPoints: ['27.5" wheels are the modern MTB standard — better rollover than 26".', 'Only Rs. 2,500 more than the 26" version for a meaningful upgrade.'], targetCustomer: 'Recreational trail riders, taller riders', commonObjections: [] },
    { id: 'bike-ral-nexus', name: 'Raleigh Nexus 27.5', brand: 'Raleigh', category: 'MTB', price: 20000, usps: ['Aluminium frame — 3-4 kg lighter than steel', 'Mechanical disc brakes — stop in any weather', 'Suspension lockout for road efficiency'], features: ['Aluminium alloy frame', 'Shimano 21-speed Tourney', 'Mechanical disc brakes', '27.5" wheels', 'Front suspension with lockout'], talkingPoints: ['This is where you step up from steel to aluminium — noticeable weight difference.', 'Disc brakes mean confident stopping in Bangalore rain.', 'Suspension lockout — lock it on road, unlock on trail. Best of both worlds.'], targetCustomer: 'Enthusiast MTB riders, weekend trail riders', commonObjections: [{ objection: 'Rs. 20K for a non-electric?', response: 'An aluminium frame lasts 15+ years and weighs 3-4 kg less. That weight difference matters on every pedal stroke. This is an investment in fitness.' }] },
    { id: 'bike-ral-summit', name: 'Raleigh Summit 29', brand: 'Raleigh', category: 'MTB', price: 27500, usps: ['29" wheels — fastest over rough terrain', 'Aluminium 6061 frame', 'Shimano Altus 24-speed'], features: ['Aluminium 6061 frame', 'Shimano Altus 24-speed (3x8)', 'Mechanical disc brakes', '29" wheels', 'Front suspension with lockout'], talkingPoints: ['29er wheels roll over everything — roots, rocks, potholes.', 'Shimano Altus is a step above Tourney — smoother, more precise shifting.', 'This is the bike for someone getting serious about trail riding.'], targetCustomer: 'Serious recreational riders, light trail enthusiasts', commonObjections: [] },
    // === RALEIGH HYBRID ===
    { id: 'bike-ral-venture', name: 'Raleigh Venture 700C', brand: 'Raleigh', category: 'Hybrid', price: 15000, usps: ['700C wheels — fast on tarmac', 'Shimano 21-speed', 'Rigid frame — light and efficient'], features: ['Steel frame', 'Shimano 21-speed', 'V-brakes', '700C wheels', 'Rigid fork'], talkingPoints: ['Perfect for someone commuting 5-15 km on city roads.', '700C wheels are larger and faster than 26" — cover more ground per pedal.', 'No suspension means lighter bike and more efficient pedaling on road.'], targetCustomer: 'Daily commuters, fitness riders', commonObjections: [] },
    // === RALEIGH KIDS ===
    { id: 'bike-ral-striker16', name: 'Raleigh Striker 16', brand: 'Raleigh', category: 'Kids', price: 6500, usps: ['Trusted Raleigh quality for kids', 'Training wheel compatible', 'Durable steel frame'], features: ['Steel frame', 'Single speed', 'Caliper brakes', '16" wheels'], talkingPoints: ['Perfect first bike for 4-6 year olds.', 'Raleigh quality means it lasts through siblings — hand it down.'], targetCustomer: 'Parents of kids 4-6 years', commonObjections: [] },
    { id: 'bike-ral-scout24', name: 'Raleigh Scout 24', brand: 'Raleigh', category: 'Kids', price: 9000, usps: ['6-speed Shimano gears', 'Grows with the child', 'V-brakes for safety'], features: ['Steel frame', '6-speed Shimano', 'V-brakes', '24" wheels'], talkingPoints: ['First geared bike for kids 9-13 — teaches them gear shifting.', 'At Rs. 9K this is a solid bike that lasts 3-4 years.'], targetCustomer: 'Kids 9-13 years, parents wanting quality', commonObjections: [] },
    // === HERO ===
    { id: 'bike-hero-sprint26', name: 'Hero Sprint Hybrid 26', brand: 'Hero', category: 'City', price: 7000, usps: ['India\'s most popular brand', 'Most affordable commuter bike', 'Spare parts available everywhere'], features: ['Steel frame', 'Single speed', 'V-brakes', '26" wheels'], talkingPoints: ['Hero is India\'s #1 cycle brand — trusted by crores of riders.', 'At Rs. 7K, this is the most affordable way to start cycling.', 'Spare parts available at any roadside shop — zero maintenance headache.'], targetCustomer: 'Budget commuters, students, daily utility riders', commonObjections: [{ objection: 'It is too basic', response: 'Basic means reliable and cheap to maintain. For a 3-5 km daily commute, you don\'t need gears or suspension — you need durability.' }] },
    { id: 'bike-hero-torque', name: 'Hero Sprint Pro Torque 26', brand: 'Hero', category: 'MTB', price: 9000, usps: ['Budget MTB with 21 gears', 'Front suspension', 'Hero reliability at MTB price'], features: ['Steel frame', 'Shimano 21-speed', 'V-brakes', '26" wheels', 'Front suspension'], talkingPoints: ['Cheapest 21-speed MTB you can buy from a trusted brand.', 'Front suspension handles rough roads and speed breakers.', 'Great first MTB for college students.'], targetCustomer: 'Students, first-time MTB buyers, budget under Rs. 10K', commonObjections: [{ objection: 'Why not spend more for a Firefox?', response: 'If budget is Rs. 9K, this is the best MTB you can get. Hero\'s steel frame is nearly indestructible. Upgrade to Firefox later when you\'re ready.' }] },
    { id: 'bike-hero-growler', name: 'Hero Sprint Growler 27.5', brand: 'Hero', category: 'MTB', price: 13000, usps: ['27.5" wheels with front disc brake', 'Shimano 21-speed', 'Best Hero MTB'], features: ['Steel frame', 'Shimano 21-speed', 'Disc (front) + V-brake (rear)', '27.5" wheels', 'Front suspension'], talkingPoints: ['Hero\'s best MTB — disc brake on front for confident stopping.', '27.5" wheels are the modern standard — better than 26".', 'At Rs. 13K, competes with Raleigh Terrain at a lower price.'], targetCustomer: 'Recreational MTB riders on a budget', commonObjections: [] },
    // === HERO KIDS ===
    { id: 'bike-hero-brat16', name: 'Hero Brat 16', brand: 'Hero', category: 'Kids', price: 4000, usps: ['Most affordable kids bike in India', 'Durable steel frame', 'Training wheels included'], features: ['Steel frame', 'Single speed', 'Caliper brakes', '16" wheels', 'Training wheels'], talkingPoints: ['At Rs. 4K, this is the entry point for a child\'s first bike.', 'Training wheels included — ready to ride out of the box.', 'Hero quality — this bike survives falls, crashes, and siblings.'], targetCustomer: 'Parents buying first bike for 4-6 year olds, gift purchases', commonObjections: [] },
    { id: 'bike-hero-blast20', name: 'Hero Blast 20', brand: 'Hero', category: 'Kids', price: 5500, usps: ['Perfect for 6-9 year olds', 'V-brakes for better stopping', 'Fun sporty design'], features: ['Steel frame', 'Single speed', 'V-brakes', '20" wheels'], talkingPoints: ['Right size for kids 6-9 years.', 'V-brakes are much better than caliper brakes — important for safety.', 'Multiple color options — let the kid choose.'], targetCustomer: 'Kids 6-9 years', commonObjections: [] },
    // === HERCULES ===
    { id: 'bike-herc-roadeo26', name: 'Hercules Roadeo A75 26', brand: 'Hercules', category: 'MTB', price: 10000, usps: ['TI Cycles quality — better build than Hero', 'Shimano 21-speed', 'Front suspension', '"Roadeo" brand recognition'], features: ['Steel Hi-Ten frame', 'Shimano 21-speed', 'V-brakes', '26" wheels', 'Front suspension'], talkingPoints: ['Hercules is made by TI Cycles — India\'s best cycle manufacturer.', 'Better build quality than Hero at just Rs. 1K more.', 'The "Roadeo" name is trusted in MTB segment.'], targetCustomer: 'Budget MTB buyers wanting better quality than Hero', commonObjections: [{ objection: 'Why not Hero? It is cheaper', response: 'TI Cycles (Hercules maker) has better quality control. The frame is stiffer, the gears shift smoother. You feel the difference on the first ride.' }] },
    { id: 'bike-herc-hank', name: 'Hercules Roadeo Hank 27.5', brand: 'Hercules', category: 'MTB', price: 14000, usps: ['27.5" with mechanical disc brakes', 'Shimano 21-speed', 'TI Cycles reliability'], features: ['Steel frame', 'Shimano 21-speed', 'Mechanical disc brakes', '27.5" wheels', 'Front suspension'], talkingPoints: ['Disc brakes AND 27.5" wheels at Rs. 14K — hard to beat.', 'TI Cycles backing means spare parts and service support.', 'Great middle-ground MTB for someone spending Rs. 12-15K.'], targetCustomer: 'Recreational riders wanting disc brakes at a good price', commonObjections: [] },
    { id: 'bike-herc-maverick', name: 'Hercules Roadeo Maverick 27.5', brand: 'Hercules', category: 'MTB', price: 17500, usps: ['Aluminium frame — significant weight savings', 'Disc brakes front & rear', 'Suspension lockout'], features: ['Aluminium frame', 'Shimano 21-speed', 'Mechanical disc brakes (both)', '27.5" wheels', 'Front suspension with lockout'], talkingPoints: ['First aluminium bike in the Hercules range — 3+ kg lighter than steel.', 'Dual disc brakes for maximum stopping power.', 'Suspension lockout for road efficiency.', 'At Rs. 17.5K, cheapest aluminium MTB from a major brand.'], targetCustomer: 'Enthusiast riders stepping up to aluminium', commonObjections: [{ objection: 'Why aluminium matters?', response: 'Pick up a steel bike, then pick up this one. You will feel 3 kg less. That is 3 kg less on every hill, every pedal stroke, every ride. Over 1 year, your legs thank you.' }] },
    // === FIREFOX ===
    { id: 'bike-ff-rapide', name: 'Firefox Rapide 21S 700C', brand: 'Firefox', category: 'Hybrid', price: 15000, imageUrl: 'https://choosemybicycle.com/cdn/shop/files/firefox-rapide-21s-2017-new_64e803a7-3498-4bb5-bfe2-95a5042443f5.webp?v=1769106872', usps: ['Strong Bangalore brand', '700C hybrid wheels', 'Shimano 21-speed'], features: ['Steel frame', 'Shimano 21-speed', 'V-brakes', '700C wheels', 'Rigid fork'], talkingPoints: ['Firefox is a Bangalore brand — your customers know and trust it.', '700C wheels are faster on city roads than 26" MTB wheels.', 'Perfect commuter hybrid for IT professionals.'], targetCustomer: 'Urban commuters, Bangalore IT professionals', commonObjections: [] },
    { id: 'bike-ff-roadrunner', name: 'Firefox Road Runner Pro V 700C', brand: 'Firefox', category: 'Hybrid', price: 19500, imageUrl: 'https://choosemybicycle.com/cdn/shop/files/firefox-road-runner-pro-d-plus-new_040a0e0d-0cd6-4f62-9ad2-ccbe472c502b.png?v=1769106872', usps: ['Aluminium frame — light and rust-free', 'Shimano 21-speed', 'Premium hybrid design'], features: ['Aluminium alloy frame', 'Shimano 21-speed', 'V-brakes', '700C wheels', 'Rigid fork'], talkingPoints: ['Aluminium frame means no rust — perfect for Bangalore weather.', 'Lighter than steel hybrids — you arrive less tired.', 'Good looking bike for office parking — makes a statement.'], targetCustomer: 'IT professionals, fitness riders, daily commuters 8-15 km', commonObjections: [{ objection: 'Why not an e-cycle?', response: 'If you want exercise WITH commuting, a hybrid is perfect. E-cycles are for effortless travel. Depends on your goal — fitness or convenience.' }] },
    { id: 'bike-ff-volante', name: 'Firefox Volante D 700C', brand: 'Firefox', category: 'Hybrid', price: 24000, imageUrl: 'https://choosemybicycle.com/cdn/shop/files/firefox-pronto-v-700c-ssp.jpg', usps: ['Shimano Altus 24-speed — smooth shifting', 'Mechanical disc brakes', 'Premium aluminium build'], features: ['Aluminium frame', 'Shimano Altus 24-speed', 'Mechanical disc brakes', '700C wheels', 'Rigid fork'], talkingPoints: ['Shimano Altus is a real step up from Tourney — you feel the difference.', 'Disc brakes mean you stop confidently in rain.', 'Best hybrid under Rs. 25K for serious commuters.'], targetCustomer: 'Serious commuters, fitness enthusiasts, long-distance riders', commonObjections: [] },
    { id: 'bike-ff-tremor', name: 'Firefox Tremor 26', brand: 'Firefox', category: 'MTB', price: 13000, imageUrl: 'https://choosemybicycle.com/cdn/shop/files/1_d92e0aae-b8a3-46ee-bd0d-4b353d908e6b.png?v=1769106872', usps: ['Firefox quality at entry MTB price', 'Shimano 21-speed', 'Front suspension'], features: ['Steel frame', 'Shimano 21-speed', 'V-brakes', '26" wheels', 'Front suspension'], talkingPoints: ['Firefox build quality is noticeably better than Hero/Hercules at this price.', 'Entry-level MTB that punches above its weight.', 'Great for someone wanting a brand they can be proud of.'], targetCustomer: 'First-time MTB buyers, college students', commonObjections: [] },
    { id: 'bike-ff-nuke', name: 'Firefox Nuke 29', brand: 'Firefox', category: 'MTB', price: 22000, imageUrl: 'https://choosemybicycle.com/cdn/shop/files/firefox-dominator-27-5.jpg', usps: ['29" wheels — rolls over everything', 'Aluminium frame', 'Disc brakes'], features: ['Aluminium frame', 'Shimano 21-speed', 'Mechanical disc brakes', '29" wheels', 'Front suspension'], talkingPoints: ['29" wheels are the future of MTB — faster, smoother, more stable.', 'Aluminium + disc brakes at Rs. 22K is excellent value.', 'For weekend warriors who want a serious trail bike.'], targetCustomer: 'Weekend trail riders, MTB enthusiasts', commonObjections: [] },
    { id: 'bike-ff-badattitude', name: 'Firefox Bad Attitude 8 27.5', brand: 'Firefox', category: 'MTB', price: 32000, imageUrl: 'https://choosemybicycle.com/cdn/shop/files/firefox-dominator-26.jpg', usps: ['Shimano Altus/Acera 24-speed', 'SR Suntour suspension fork', 'Premium trail MTB'], features: ['Aluminium 6061 frame', 'Shimano Altus/Acera 24-speed', 'Mechanical disc brakes', '27.5" wheels', 'SR Suntour suspension fork'], talkingPoints: ['This is where MTB gets serious — SR Suntour fork is a real suspension brand.', 'Shimano Acera gears are smooth and precise — big upgrade from Tourney.', 'For the customer who rides trails every weekend.'], targetCustomer: 'Enthusiast trail riders, cycling club members', commonObjections: [] },
    // === FIREFOX ROAD ===
    { id: 'bike-ff-strada', name: 'Firefox Strada 700C', brand: 'Firefox', category: 'Road', price: 24000, imageUrl: 'https://choosemybicycle.com/cdn/shop/files/firefox-spirit-new.png', usps: ['Entry road bike with drop handlebars', 'Shimano Claris 16-speed', 'Road bike geometry'], features: ['Aluminium frame', 'Shimano Claris 16-speed (2x8)', 'Caliper brakes', '700C wheels', 'Drop handlebars'], talkingPoints: ['First real road bike for someone stepping up from hybrid.', 'Drop bars give you multiple hand positions — less fatigue on long rides.', 'Shimano Claris is reliable road groupset — smooth 16-speed shifting.'], targetCustomer: 'Aspiring road cyclists, fitness riders wanting speed', commonObjections: [{ objection: 'Drop bars look uncomfortable', response: 'You actually get 3 hand positions — tops, hoods, and drops. More comfortable on long rides than flat bars because you can switch. Try it for 5 minutes.' }] },
    // === FIREFOX KIDS ===
    { id: 'bike-ff-flipflop', name: 'Firefox Flip Flop 20', brand: 'Firefox', category: 'Kids', price: 7500, imageUrl: 'https://choosemybicycle.com/cdn/shop/files/firefox-pirate-3-0-new_47ddf669-695f-4ff6-8a7c-ec68543ebd29.png', usps: ['Firefox quality for kids', 'Fun design', 'V-brakes for safety'], features: ['Steel frame', 'Single speed / 6-speed', 'V-brakes', '20" wheels'], talkingPoints: ['Firefox quality means this bike lasts through growth spurts.', 'Better brakes and build than Hero kids bikes.', 'Your kid rides the same brand as IT professionals — that is cool.'], targetCustomer: 'Kids 6-9 years, parents wanting premium kids bike', commonObjections: [] },
    { id: 'bike-ff-trooper', name: 'Firefox Trooper 24', brand: 'Firefox', category: 'Kids', price: 10500, usps: ['21-speed gears for growing kids', 'V-brakes', 'Junior MTB design'], features: ['Steel frame', 'Shimano 21-speed', 'V-brakes', '24" wheels'], talkingPoints: ['Full 21-speed gears — this bike grows with the child into teenage years.', 'MTB design means it handles Bangalore roads and trails.', 'At Rs. 10.5K, last bike before they move to adult size.'], targetCustomer: 'Kids 10-14 years, pre-teen riders', commonObjections: [] },
    // === MONTRA ===
    { id: 'bike-mon-trance', name: 'Montra Trance Pro 700C', brand: 'Montra', category: 'Hybrid', price: 17500, usps: ['TI Cycles premium brand', 'Aluminium frame', 'Shimano 21-speed hybrid'], features: ['Aluminium alloy frame', 'Shimano 21-speed', 'V-brakes', '700C wheels', 'Rigid fork'], talkingPoints: ['Montra is TI Cycles\' performance brand — same factory, premium specs.', 'Aluminium + 700C = light and fast on city roads.', 'Popular with Bangalore cycling groups.'], targetCustomer: 'Fitness riders, cycling club beginners, IT commuters', commonObjections: [] },
    { id: 'bike-mon-blues', name: 'Montra Blues 1.1 700C', brand: 'Montra', category: 'Hybrid', price: 22000, usps: ['Shimano Altus 24-speed', 'Mechanical disc brakes', 'Aluminium 6061 frame'], features: ['Aluminium 6061 frame', 'Shimano Altus 24-speed', 'Mechanical disc brakes', '700C wheels', 'Rigid fork'], talkingPoints: ['The sweet spot hybrid — Altus gears, disc brakes, aluminium frame.', 'Everything you need for daily commute AND weekend fitness rides.', 'Great resale value — Montra holds price well.'], targetCustomer: 'Serious commuters, weekend fitness riders', commonObjections: [] },
    { id: 'bike-mon-celtic', name: 'Montra Celtic 1.1', brand: 'Montra', category: 'Road', price: 24000, usps: ['Best value entry road bike in India', 'Shimano Claris 16-speed', 'Drop bar road geometry'], features: ['Aluminium frame', 'Shimano Claris 16-speed (2x8)', 'Caliper brakes', '700C wheels', 'Drop handlebars'], talkingPoints: ['Montra Celtic is THE entry road bike in India — most cycling clubs recommend it.', 'Shimano Claris groupset is reliable and smooth.', 'If a customer says they want to start road cycling, this is the answer.'], targetCustomer: 'Aspiring road cyclists, cycling club beginners', commonObjections: [{ objection: 'Why road bike over hybrid?', response: 'Road bikes are 2-3 km/hr faster at the same effort. Drop bars reduce wind resistance. If you want fitness + speed, road bike wins.' }] },
    { id: 'bike-mon-celtic21', name: 'Montra Celtic 2.1', brand: 'Montra', category: 'Road', price: 33000, usps: ['Shimano Sora 18-speed — serious road groupset', 'Aluminium 6061 frame', 'Performance road geometry'], features: ['Aluminium 6061 frame', 'Shimano Sora 18-speed (2x9)', 'Caliper brakes', '700C wheels', 'Drop handlebars'], talkingPoints: ['Shimano Sora is a HUGE jump from Claris — pros train on Sora.', 'If they are riding 50+ km on weekends, Sora makes every km smoother.', 'Best road bike under Rs. 35K in India.'], targetCustomer: 'Intermediate road cyclists, people upgrading from entry road bikes', commonObjections: [] },
    { id: 'bike-mon-madrock', name: 'Montra Madrock 27.5', brand: 'Montra', category: 'MTB', price: 20000, usps: ['Aluminium MTB from TI Cycles', 'Shimano 21-speed', 'Mechanical disc brakes'], features: ['Aluminium frame', 'Shimano 21-speed', 'Mechanical disc brakes', '27.5" wheels', 'Front suspension'], talkingPoints: ['Premium aluminium MTB at Rs. 20K from TI Cycles.', 'Better components and finish than Hercules at this price.', 'For the rider who wants a trail-ready bike with brand pedigree.'], targetCustomer: 'Recreational MTB riders, weekend trail enthusiasts', commonObjections: [] },
    // === GIANT ===
    { id: 'bike-giant-atx', name: 'Giant ATX 27.5', brand: 'Giant', category: 'MTB', price: 30000, usps: ['World\'s #1 bicycle manufacturer', 'ALUXX aluminium technology', 'Premium build quality'], features: ['Aluminium ALUXX frame', 'Shimano Tourney 21-speed', 'Mechanical disc brakes', '27.5" wheels', 'Front suspension'], talkingPoints: ['Giant is the world\'s LARGEST bicycle manufacturer — global quality.', 'ALUXX aluminium is their proprietary alloy — lighter and stronger.', 'When someone says "I want the best quality frame," show them Giant.', 'This bike will last 10-15 years with basic maintenance.'], targetCustomer: 'Premium buyers, quality-conscious riders, cycling enthusiasts', commonObjections: [{ objection: 'Rs. 30K for a non-electric without many gears?', response: 'You are paying for the FRAME. Giant ALUXX is aircraft-grade aluminium. A cheap frame flexes and wastes your energy. This frame transfers every pedal stroke to the road.' }] },
    { id: 'bike-giant-escape', name: 'Giant Escape 3 700C', brand: 'Giant', category: 'Hybrid', price: 32500, usps: ['Premium hybrid for serious commuters', 'ALUXX aluminium frame', 'Shimano 24-speed'], features: ['Aluminium ALUXX frame', 'Shimano 24-speed', 'V-brakes', '700C wheels', 'Rigid fork'], talkingPoints: ['The Giant Escape is the world\'s best-selling hybrid — for a reason.', 'ALUXX frame is lighter than any Indian brand at this price.', 'If you commute 10+ km daily and want the best ride quality, this is it.'], targetCustomer: 'Premium commuters, fitness-focused riders, quality seekers', commonObjections: [] },
  ];

export const extraScenarios = [
];

